### ISSUE TITLE
ClassCastException - [B cannot be cast to java.lang.Long using Jedis integration

### ISSUE THREAD

**Issue by koguroff** [bucket4j/bucket4j#330]
Hi
I'm using your Redis integration
```
    api "com.bucket4j:bucket4j_jdk8-core:8.1.0"
    api "com.bucket4j:bucket4j_jdk8-redis:8.1.0"
```
```
@Bean
    SpringDataRedisBasedProxyManager bucketRedisProxyManager(RedisConfiguration configuration) {
        GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        poolConfig.setMaxTotal(configuration.maxConnections);

        List<HostAndPort> shards = configuration.hosts.stream()
                .map(hostAndPort -> new HostAndPort(hostAndPort.getHost(),
                        hostAndPort.getPort()))
                .collect(Collectors.toList());

        JedisClusterConnection jedisClusterConnection = new JedisClusterConnection(new JedisCluster(new HashSet<>(shards), configuration.timeoutMs, poolConfig));
        return SpringDataRedisBasedProxyManager.builderFor(jedisClusterConnection)
                .withExpirationStrategy(ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(10)))
                .build();
    }
```
```
private Bucket configureRatelimiter(Configuration configuration) {
        BucketConfiguration bucketConfiguration = BucketConfiguration.builder()
                .addLimit(Bandwidth.simple(configuration.rate, configuration.ratePeriod))
                .build();

        return proxyManager.builder().build(configuration.bucketKey.getBytes(), bucketConfiguration);
    }
```
With such configuration under multithreaded load (server) some calls to `bucket.tryConsume()` (I would say 2-4%) cause an error

```
org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.Long
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:53)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:43)
	at org.springframework.data.redis.connection.jedis.JedisClusterConnection.convertJedisAccessException(JedisClusterConnection.java:777)
	at org.springframework.data.redis.connection.jedis.JedisClusterScriptingCommands.convertJedisAccessException(JedisClusterScriptingCommands.java:146)
	at org.springframework.data.redis.connection.jedis.JedisClusterScriptingCommands.eval(JedisClusterScriptingCommands.java:114)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.eval(DefaultedRedisConnection.java:1433)
	at io.github.bucket4j.redis.spring.cas.SpringDataRedisBasedProxyManager.compareAndSwap(SpringDataRedisBasedProxyManager.java:128)
	at io.github.bucket4j.redis.spring.cas.SpringDataRedisBasedProxyManager.access$400(SpringDataRedisBasedProxyManager.java:41)
	at io.github.bucket4j.redis.spring.cas.SpringDataRedisBasedProxyManager$1.compareAndSwap(SpringDataRedisBasedProxyManager.java:80)
	at io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager.execute(AbstractCompareAndSwapBasedProxyManager.java:79)
	at io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager.execute(AbstractCompareAndSwapBasedProxyManager.java:51)
	at io.github.bucket4j.distributed.proxy.AbstractProxyManager$DefaultRemoteBucketBuilder$1.execute(AbstractProxyManager.java:197)
	at io.github.bucket4j.distributed.proxy.DefaultBucketProxy.execute(DefaultBucketProxy.java:222)
	at io.github.bucket4j.distributed.proxy.DefaultBucketProxy.tryConsumeImpl(DefaultBucketProxy.java:83)
	at io.github.bucket4j.AbstractBucket.tryConsume(AbstractBucket.java:201)
```

This exception looks very much alike of this issue https://github.com/redis/jedis/issues/186 caused by reusing same Jedis instance in several threads.

**Comment by vladimir-bukhtoyarov** [comment]
Looks that SpringDataRedisBasedProxyManager was not tested with Jedis. There is only test with Letuce is https://github.com/bucket4j/bucket4j/blob/master/bucket4j-redis/src/test/java/io/github/bucket4j/redis/spring/cas/SpringBasedProxyManagerFixedTtlTest.java#L43 which is threadsafe, while Jedis is not threadsafe. I will create fix at weekend. If you are blocked try to switch ot Letucci.

**Comment by koguroff** [comment]
Unfortunately, [JedisBasedProxyManager](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-redis/src/main/java/io/github/bucket4j/redis/jedis/cas/JedisBasedProxyManager.java) does not support JedisCluster.
But it's not a blocker for the time being. 
Thanks for the quick response.

**Comment by vladimir-bukhtoyarov** [comment]
@koguroff 

Redis Cluster support has been added for both Letuce and Jedis in release ```8.2.RC2```.
```xml
<dependency>
    <groupId>com.bucket4j</groupId>
    <artifactId>bucket4j-redis</artifactId>
    <version>8.2.RC2</version>
</dependency>
```

Example usage for Jedis:
```java
JedisCluster jedisCluster = ...;
ProxyManager<byte[]> proxyManager = JedisBasedProxyManager.builderFor(jedisCluster)
                .withExpirationStrategy(ExpirationAfterWriteStrategy.fixedTimeToLive(Duration.ofSeconds(10)))
                .build();
```

Example usage for Letuce:
```java
RedisClusterClient redisClusterClient = ...;
ProxyManager<byte[]> proxyManager = LettuceBasedProxyManager.builderFor(redisClusterClient)
                .withExpirationStrategy(ExpirationAfterWriteStrategy.fixedTimeToLive(Duration.ofSeconds(10)))
                .build();
```

Also, support for spring-data-redis has been removed as infinite source of problems.
