### ISSUE TITLE
SocketTimeoutException on connecting to Azure Redis 

### ISSUE THREAD

**Issue by sachinkumar579** [bucket4j/bucket4j#476]
Below code works perfectly fine while connecting to local Redis with localhost url and default password. It seems to return SocketException while connecting to Azure Redis . ssl has been enabled in application properties spring.data.redis.ssl.enabled=true . Any other changes required while connecting to Azure Redis ?

Java Code snippet 

@Component
public class RedisConfig {

	@Bean
	public RedisCacheManager cacheManager(RedisConnectionFactory connectionFactory) {
		return RedisCacheManager.create(connectionFactory);
	}

	@Bean
	ProxyManager<String> proxyManager(CacheManager cacheManager) {
		return JedisBasedProxyManager.builderFor(createJedisClient())
		    .withExpirationStrategy(ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(15)))
			    .withKeyMapper(Mapper.STRING)
			    .build();
	}

	private static JedisPool createJedisClient() {
		String cacheHostname = "test.redis.cache.windows.net";
		String cachekey = "password";
		return new JedisPool(cacheHostname, 6380, "test",cachekey);
	}
}	

@RestController
public class Controller {

	@Autowired
	private ProxyManager<String> proxyManager;

	private static final long REQS_IN_15_MINS_WINDOW = 5;
	private static final Duration DURATION_15SECS = Duration.ofSeconds(15);

	@GetMapping("/test")
	public void test() {
		BucketConfiguration configuration = BucketConfiguration.builder().addLimit(
				Bandwidth.classic(REQS_IN_15_MINS_WINDOW, Refill.intervally(REQS_IN_15_MINS_WINDOW, DURATION_15SECS)))
				.build();

		Bucket bucket = proxyManager.builder().build("test", configuration);

		System.out.println(bucket.getAvailableTokens());
	}
}

Error logs : 
2024-04-22T00:35:04.280+05:30 ERROR 19732 --- [nio-8081-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out] with root cause

java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[na:na]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966) ~[na:na]
	at java.base/java.io.InputStream.read(InputStream.java:218) ~[na:na]
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:245) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:47) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:135) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:221) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:269) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.helloOrAuth(Connection.java:493) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:402) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.<init>(Connection.java:68) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Jedis.<init>(Jedis.java:220) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:170) ~[jedis-5.0.2.jar:na]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[commons-pool2-2.12.0.jar:2.12.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[commons-pool2-2.12.0.jar:2.12.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[commons-pool2-2.12.0.jar:2.12.0]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:38) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:17) ~[jedis-5.0.2.jar:na]
	at io.github.bucket4j.redis.jedis.cas.JedisBasedProxyManager$1.get(JedisBasedProxyManager.java:59) ~[bucket4j-redis-8.10.1.jar:8.10.1]
	at io.github.bucket4j.redis.jedis.cas.JedisBasedProxyManager$4.getStateData(JedisBasedProxyManager.java:153) ~[bucket4j-redis-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.Timeout$1.call(Timeout.java:54) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager.execute(AbstractCompareAndSwapBasedProxyManager.java:74) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager.execute(AbstractCompareAndSwapBasedProxyManager.java:53) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.AbstractProxyManager$DefaultRemoteBucketBuilder$1.lambda$execute$0(AbstractProxyManager.java:203) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.ExecutionStrategy$1.execute(ExecutionStrategy.java:43) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.AbstractProxyManager$DefaultRemoteBucketBuilder$1.execute(AbstractProxyManager.java:204) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.DefaultBucketProxy.execute(DefaultBucketProxy.java:208) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at io.github.bucket4j.distributed.proxy.DefaultBucketProxy.getAvailableTokens(DefaultBucketProxy.java:131) ~[bucket4j-core-8.10.1.jar:8.10.1]
	at com.example.demo.Controller.test(Controller.java:33) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.1.6.jar:6.1.6]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.20.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.20.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.6.jar:6.1.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.6.jar:6.1.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.6.jar:6.1.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.6.jar:6.1.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-web-6.1.6.jar:6.1.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.6.jar:6.1.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.6.jar:6.1.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.6.jar:6.1.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:175) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:150) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by vladimir-bukhtoyarov** [comment]
Hello @sachinkumar579 

>  Any other changes required while connecting to Azure Redis?

You need to address this question directly to Azure support, or to Jedis maintainers, because this question is out of scope for Bucket4j library.

**Comment by sachinkumar579** [comment]
@vladimir-bukhtoyarov  Thank you for the immediate response. nvm , it worked with url 
rediss://default:password@test.redis.cache.windows.net:6380 .

**Comment by sachinkumar579** [comment]
it worked with url
 rediss://default:[password@test.redis.cache.windows.net](mailto:password@test.redis.cache.windows.net):6380 .
